user: jboss
home_dir: /home/{{user}}
lab_home_dir: /home/{{user}}/lab
install_script_dir: /opt/install/scripts

bpms_mysql_db_name: bpms
bpms_mysql_user: jboss
bpms_mysql_password: jboss

dashbuilder_mysql_db_name: dashbuilder
dashbuilder_mysql_user: dashbuilder
dashbuilder_mysql_password: jboss

pquote_reporting_mysql_db_name: pquote_reporting
pquote_reporting_mysql_user: pquote
pquote_reporting_mysql_password: jboss

